//=============================================================================
// LadderCTF
//=============================================================================
class AMLadderCTF extends LadderCTF Config(AMLadder);

defaultproperties
{
      Matches=24
      bTeamGame=True
      MapPrefix="CTF-"
      Maps(0)="Tutorial.unr"
      Maps(1)="Niven.unr"
      Maps(2)="Face.unr"
      Maps(3)="EternalCave.unr"
      Maps(4)="Coret.unr"
      Maps(5)="Face-SE.unr"
      Maps(6)="Gauntlet.unr"
      Maps(7)="Command.unr"
      Maps(8)="Face][.unr"
      Maps(9)="Cybrosis][.unr"
      Maps(10)="EpicBoy.unr"
      Maps(11)="Hydro16.unr"
      Maps(12)="November.unr"
      Maps(13)="Dreary.unr"
      Maps(14)="LavaGiant.unr"
      Maps(15)="Noxion16.unr"
      Maps(16)="Ratchet.unr"
      Maps(17)="Nucleus.unr"
      Maps(18)="Beatitude.unr"
      Maps(19)="HallOfGiants.unr"
      Maps(20)="Kosov.unr"
      Maps(21)="Darji16.unr"
      Maps(22)="Orbital.unr"
      Maps(23)="High.unr"
      MapAuthors(0)="Cliff Bleszinski"
      MapAuthors(1)="Alan Willard"
      MapAuthors(2)="Cedric Fiorentino"
      MapAuthors(3)="Juan Pancho Eekels"
      MapAuthors(4)="Alan Willard"
      MapAuthors(5)="Cedric Fiorentino"
      MapAuthors(6)="Cliff Bleszinski"
      MapAuthors(7)="Elliot Cannon"
      MapAuthors(8)="Cedric Fiorentino"
      MapAuthors(9)="Alan Willard"
      MapAuthors(10)="Warren Marshall"
      MapAuthors(11)="Sidney Rauchberger"
      MapAuthors(12)="Elliot Cannon"
      MapAuthors(13)="Shane Caudle"
      MapAuthors(14)="Juan Pancho Eekels"
      MapAuthors(15)="Sidney Rauchberger"
      MapAuthors(16)="Sidney Rauchberger"
      MapAuthors(17)="Cedric Fiorentino"
      MapAuthors(18)="Sidney Rauchberger"
      MapAuthors(19)="Juan Pancho Eekels"
      MapAuthors(20)="Cedric Fiorentino"
      MapAuthors(21)="Alan Willard"
      MapAuthors(22)="Dave Ewing"
      MapAuthors(23)="Cedric Fiorentino"
      MapTitle(0)="CTF Tutorial"
      MapTitle(1)="Niven Experimental Lab"
      MapTitle(2)="Facing Worlds"
      MapTitle(3)="Eternal Cave"
      MapTitle(4)="Coret Facility"
      MapTitle(5)="Facing Worlds Rematch"
      MapTitle(6)="The Iron Gauntlet"
      MapTitle(7)="The Last Command"
      MapTitle(8)="Facing Worlds Redux"
      MapTitle(9)="Cybrosis Redux"
      MapTitle(10)="Epic Boy"
      MapTitle(11)="Hydro Bases"
      MapTitle(12)="November Sub Pen"
      MapTitle(13)="Dreary Outpost"
      MapTitle(14)="Lava Giant"
      MapTitle(15)="Noxion Base"
      MapTitle(16)="Ratchet"
      MapTitle(17)="Nucleus Power Plant"
      MapTitle(18)="Temple of Beatitude"
      MapTitle(19)="Hall Of Giants"
      MapTitle(20)="Kosov Canyon"
      MapTitle(21)="Darji Outpost #16-A"
      MapTitle(22)="Orbital Station #12"
      MapTitle(23)="High Towers"
      MapDescription(0)="Learn the basic rules and systems of Capture the Flag in this special training environment. Test your skills against an untrained enemy team before entering the tournament proper."
      MapDescription(1)="An experimental orbital nuclear reactor; abandoned after funding for the project dried up. High radiation levels and waste leakage offer an environmental challenge for Tournament combatants."
      MapDescription(2)="This ancient asteroid has been converted to an Arena for the Tournament. It is highly dangerous due to aberrant gravitational properties and, of course, the snipers from the other team."
      MapDescription(3)="Ruins belonging to an unknown race, acquired by Liandri Corporation's Xenobiology Division for research and excavation. Deemed a 'valuable and entertaining venue' by the Tournament Board after 17 XD archeologists fell to their deaths."
      MapDescription(4)="Built into a mountaintop on the Coret moon, this facility was once the waypoint between the Interstellar zonegate in orbit over the moon and the Zeto Research Station located half the moon away in the frozen wastes."
      MapDescription(5)="No description available."
      MapDescription(6)="Not all environments are retrofitted Liandri real estate. The Gauntlet is one of a small number of highly stylized combat arenas specifically designed for the Tournament. This particular venue has been customized for teamplay."
      MapDescription(7)="The Last Command is a fully functional Nuclear Processing Station owned by the LC. This facility's system oriented layout makes an ideal proving grounds for the Capture the Flag Tournament matches. High Tech voluminous industrial architecture paired with curving maintenance corridors means fighting here will require quick reaction times if your team plans on surviving."
      MapDescription(8)="After a cataclysmic disaster with a meteor that destroyed the original pair of facing temples and claiming 8 lives, including 4 Necris and 4 members of Raw Steel, The members of the Tournament insisted that Liandri build an almost-identical, but semi-resistant to a meteor attack, version of the famous Capture The Flag stop in the Tournament. Liandri listened, and a year after the destruction of the first, a second was introduced, with bases roughly 20% closer and featuring more sniping spots. Fans loved the non-stop action that kept them on the edge of their seats. Neurovision, the Tournament's leading broad caster, loved how much money came in as well in the following Tournaments."
      MapDescription(9)="No description available."
      MapDescription(10)="No description available."
      MapDescription(11)="This enormous hydroelectric plant used to power the colonies on Vesuvius 9 until a mysterious virus killed everyone off. Now that a few years have passed, Liandri officials have declared the plant safe for combat (safe is relative to Liandri officials)."
      MapDescription(12)="Battle around a retired November class nuclear submarine docked in an underground pen. This relic, from the First Cold War, still includes machinegun nests and defensive positions key to victory."
      MapDescription(13)="This distant wastemarsh of Vandaron 3 is said to be the wettest place in the galaxy. A post dreaded by soldiers due to its remote location, cramped quarters and maddening echo of ever beating rain."
      MapDescription(14)="This volatile world has an extremely low orbit around a superdense gas giant. The resulting gravitational forces have caused the planetary mantle to collapse. Combatants are issued special gravbelts for each match."
      MapDescription(15)="No description available."
      MapDescription(16)="No description available."
      MapDescription(17)="No description available."
      MapDescription(18)="No description available."
      MapDescription(19)="Every now and then, Liandri uses a venue occupied by the Skaarj and its elite. This is such a venue. Used by the Skaarj for training purposes, Never did they think the NEG would favor a Team game in, or even locate, this unbelievably huge corridor."
      MapDescription(20)="Along the infamous Pain River in Na Pali are these 2 abandoned temples. Liandri eventually found these temples, but, shockingly, not before the Dark Phalanx found it and called it their own. Liandri innocently blew huge money to have this as just another Tournament stop."
      MapDescription(21)="No description available."
      MapDescription(22)="The interior of this dual-sided space station may appear incomplete, but much functionality was never completed when funding ran out due to corrupt contractors and irresponsible administrators. As usual, the savvy Liandri location scouts caught wind of this and picked the station up at a discount for inclusion in the tourney."
      MapDescription(23)="No description available."
      RankedGame(0)=1
      RankedGame(1)=1
      RankedGame(2)=1
      RankedGame(3)=1
      RankedGame(4)=1
      RankedGame(5)=1
      RankedGame(6)=2
      RankedGame(7)=2
      RankedGame(8)=2
      RankedGame(9)=2
      RankedGame(10)=2
      RankedGame(11)=3
      RankedGame(12)=3
      RankedGame(13)=3
      RankedGame(14)=3
      RankedGame(15)=3
      RankedGame(16)=4
      RankedGame(17)=4
      RankedGame(18)=4
      RankedGame(19)=4
      RankedGame(20)=4
      RankedGame(21)=5
      RankedGame(22)=5
      RankedGame(23)=6
      GoalTeamScore(0)=3
      GoalTeamScore(1)=2
      GoalTeamScore(2)=3
      GoalTeamScore(3)=3
      GoalTeamScore(4)=3
      GoalTeamScore(5)=3
      GoalTeamScore(6)=3
      GoalTeamScore(7)=3
      GoalTeamScore(8)=3
      GoalTeamScore(9)=3
      GoalTeamScore(10)=3
      GoalTeamScore(11)=3
      GoalTeamScore(12)=3
      GoalTeamScore(13)=3
      GoalTeamScore(14)=3
      GoalTeamScore(15)=3
      GoalTeamScore(16)=3
      GoalTeamScore(17)=4
      GoalTeamScore(18)=4
      GoalTeamScore(19)=4
      GoalTeamScore(20)=4
      GoalTeamScore(21)=4
      GoalTeamScore(22)=5
      GoalTeamScore(23)=5
      MatchInfo(0)="Botpack.RatedMatchCTFTUT"
      MatchInfo(1)="AMLadder.RatedMatchCTF1AM"
      MatchInfo(2)="AMLadder.RatedMatchCTF2AM"
      MatchInfo(3)="AMLadder.RatedMatchCTF3AM"
      MatchInfo(4)="AMLadder.RatedMatchCTF4AM"
      MatchInfo(5)="AMLadder.RatedMatchCTF5AM"
      MatchInfo(6)="AMLadder.RatedMatchCTF6AM"
      MatchInfo(7)="AMLadder.RatedMatchCTF7AM"
      MatchInfo(8)="AMLadder.RatedMatchCTF8AM"
      MatchInfo(9)="AMLadder.RatedMatchCTF9AM"
      MatchInfo(10)="AMLadder.RatedMatchCTF10AM"
      MatchInfo(11)="AMLadder.RatedMatchCTF11AM"
      MatchInfo(12)="AMLadder.RatedMatchCTF12AM"
      MatchInfo(13)="AMLadder.RatedMatchCTF13AM"
      MatchInfo(14)="AMLadder.RatedMatchCTF14AM"
      MatchInfo(15)="AMLadder.RatedMatchCTF15AM"
      MatchInfo(16)="AMLadder.RatedMatchCTF16AM"
      MatchInfo(17)="AMLadder.RatedMatchCTF17AM"
      MatchInfo(18)="AMLadder.RatedMatchCTF18AM"
      MatchInfo(19)="AMLadder.RatedMatchCTF19AM"
      MatchInfo(20)="AMLadder.RatedMatchCTF20AM"
      MatchInfo(21)="AMLadder.RatedMatchCTF21AM"
      MatchInfo(22)="AMLadder.RatedMatchCTF22AM"
      MatchInfo(23)="AMLadder.RatedMatchCTF23AM"
}
